# Base model registry
model_registry = {'SI':  {'graph_type': 'stream',
                          'model_type': 'spike_input',
                          'param': {}, 'state': {}},
                  'SC':  {'graph_type': 'edge',
                          'model_type': 'spike_clamp',
                          'param': {},
                          'state': {'delay':    {'mapfrom': 'delay',     'default': 1.0, 'unit': 'tick'}}},
                  'IN':  {'graph_type': 'input',
                          'model_type': 'simple_input',
                          'param': {},
                          'state': {'I_clamp':  {'mapfrom': None,        'default': 0.0}}},
                  'LIF': {'graph_type': 'node',
                          'model_type': 'simple_neuron',
                          'param': {},
                          'state': {'v':        {'mapfrom': 'voltage',   'default': 0.0},
                                    'v_thresh': {'mapfrom': 'threshold', 'default': 1.0},
                                    'v_reset':  {'mapfrom': 'reset',     'default': 0.0},
                                    'v_bias':   {'mapfrom': 'bias',      'default': 0.0},
                                    'v_leak':   {'mapfrom': 'leak',      'default': 1.0},
                                    'I_syn':    {'mapfrom': None,        'default': 0.0}}},
                  'PSP': {'graph_type': 'edge',
                          'model_type': 'simple_synapse',
                          'param': {},
                          'state': {'delay':    {'mapfrom': 'delay',     'default': 1.0, 'unit': 'tick'},
                                    'weight':   {'mapfrom': 'weight',    'default': 1.0}}}
                 }